apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: rcs
build:
  artifacts:
  - image: rcs
    sync:
      infer: ["scripts/**"]
    docker:
      dockerfile: Dockerfile
deploy:
  statusCheckDeadlineSeconds: 20
  kubectl:
    manifests:
    - rcs.yaml
