apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-openidm
  labels:
    app: postgres-openidm
spec:
  selector:
    matchLabels:
      app: postgres-openidm
  template:
    metadata:
      labels:
        app: postgres-openidm
    spec:
      containers:
      - name: postgres
        image: "postgres:10.5-alpine"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: POSTGRES_USER
          value: "openidm"
          # Required for pg_isready in the health probes.
        - name: PGUSER
          value: "openidm"
        - name: POSTGRES_DB
          value: ""
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          value: "openidm"
        # Adding the default values here just to provide a place to tune further
        args: ['-c','shared_buffers=128MB','-c','max_connections=100']
        ports:
        - name: postgresql
          containerPort: 5432
        livenessProbe:
          exec:
            command:
            - pg_isready
          initialDelaySeconds: 30
          timeoutSeconds: 3
        readinessProbe:
          exec:
            command:
            - pg_isready
          initialDelaySeconds: 30
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgres-openidm
spec:
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: postgres-openidm