apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rcs
spec:
  replicas: 2
  serviceName: rcs
  selector:
    matchLabels:
      app: rcs
  template:
    metadata:
      labels:
        app: rcs
    spec:
      containers:
      - image:  rcs
        name: rcs
        command:
        - bash
        - -c
        - echo $(HOST_IP) $(HOST_NAME) >> /etc/hosts;
          export OPENICF_OPTS=-Dconnectorserver.connectorServerName=$HOSTNAME && /opt/openicf/bin/docker-entrypoint.sh;
        resources:
          requests:
            memory: "500Mi"
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: HOST_NAME
          value: default.iam.example.com
